In [10]:
for i in range (0,4):
    for j in range(0,4):
        if i+j<=2:
            print(" ",end=" ")
        if i+j>=3:
            print("*",end=" ")
    print()
    

      * 
    * * 
  * * * 
* * * * 


In [12]:
n=input("enter the name")
for i in range(len(n)):
    for j in range(0,i+1):
        print(n[i],end=" ")
    print()

enter the namelubna
l 
u u 
b b b 
n n n n 
a a a a a 


In [14]:
rec={}
n=int(input("enter the number of students"))
i=1
while i<=n:
    name=input("enter the student name:")
    marks=input("enter the % of the student")
    rec[name]=marks
    i+=1
print("name of the student","\t","%of marks")
for x in rec:
    print("\t",x,"\t\t",rec[x])

enter the number of students2
enter the student name:amritha
enter the % of the student98
enter the student name:thirsha
enter the % of the student98.8
name of the student 	 %of marks
	 amritha 		 98
	 thirsha 		 98.8


In [17]:
d={100:"hello",2:"mite",300:"lubna"}
print(d)

{100: 'hello', 2: 'mite', 300: 'lubna'}


In [18]:
d[2]="bye"
print(d)

{100: 'hello', 2: 'bye', 300: 'lubna'}


In [20]:
del d[300]
print(d)

{100: 'hello', 2: 'bye'}


In [21]:
d.clear()

In [22]:
del d

In [23]:
print(d)

NameError: name 'd' is not defined

In [28]:
dict={100:"hello",2:"mite",300:"lubna"}
print(dict)
print(len(dict))

{100: 'hello', 2: 'mite', 300: 'lubna'}
3


In [29]:
word=input("enter any word:")
d={}
for x in word:
    d[x]=d.get(x,0)+1
for k,v in d.items():
    print(k,"occured",v,"times")

enter any word:association
a occured 2 times
s occured 2 times
o occured 2 times
c occured 1 times
i occured 2 times
t occured 1 times
n occured 1 times


In [36]:
word=input("enter any word:")
d={}
vowels={'a','e','i','o','u'}
for i in word:
    if i in vowels:
        d[i]=d.get(i,0)+1
for k,v in d.items():
    print(k,"occured",v,"times")


enter any word:association
a occured 2 times
o occured 2 times
i occured 2 times


In [35]:
squares={x:x*x for x in range(1,6)}
print(squares)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [38]:
n=[1,2,3,4,5,5,5,5]
print(n.count(5))
print(n.index(5))


4
4


In [40]:
n=[1,2,3,4,5]
n.insert(1,888)
print(n)

[1, 888, 2, 3, 4, 5]


In [42]:
list1=[1,2,3,"hello"]
list2=[4,5,6,"india"]
list1.extend(list2)
print(list1)

[1, 2, 3, 'hello', 4, 5, 6, 'india']


###remove

In [43]:
n.remove(2)

In [44]:
print(n)


[1, 888, 3, 4, 5]


### remove

In [45]:
n.pop()
print(n)

[1, 888, 3, 4]


In [46]:
n.reverse()
print(n)

[4, 3, 888, 1]


In [47]:
n.sort()
print(n)

[1, 3, 4, 888]


In [49]:
d.sort()
print(d)

AttributeError: 'dict' object has no attribute 'sort'

In [50]:
n.sort(reverse=True)
print(n)

[888, 4, 3, 1]


In [51]:
x=[10,20,30,40]
y=x[:]
y[1]=777
print(x)
print(y)


[10, 20, 30, 40]
[10, 777, 30, 40]


In [52]:
x=[10,20,30,40]
y=x
y[1]=777
print(x)
print(y)


[10, 777, 30, 40]
[10, 777, 30, 40]


In [53]:
x=[10,20,30,40]
y=x.copy()
y[1]=777
print(x)
print(y)


[10, 20, 30, 40]
[10, 777, 30, 40]


In [54]:
a=[10,20,30,40]
b=[50,60,70]
c=a+b
print(c)


[10, 20, 30, 40, 50, 60, 70]


In [55]:
x=[10,20,30]
y=x*3
print(y)


[10, 20, 30, 10, 20, 30, 10, 20, 30]


In [56]:
x=["MITE","mangalore","NITTE"]
y=["MITE","mangalore","NITTE"]
x==y
x!=y
z=["MITE","mangalore","NITTE"]
x==z

True

In [58]:
M=[10,20,30,[40,50,60,70]]
M[3]
M[3][1]

50

In [59]:
n=[1,2,3,4]
print(4 in n)


True


In [60]:
s=[2**x for x in range(1,6)]
print(s)

[2, 4, 8, 16, 32]


In [61]:
words=["mite","nitte","alvas"]
l=[w[0] for w in words]
print(l)

['m', 'n', 'a']


In [72]:
def prime(n):
    flag=0
    for i in range (2,n//2):
        if n%i==0:
            flag=1
            break
    
    if flag==1:
        print("not prime")
    else:
        print(" prime")
n=int(input("enter the number"))
prime(n)


enter the number2
 prime


In [73]:
seq=[1,2,3,4,5]
lambda var:var*2
list(map(lambda var:var*2,seq))

[2, 4, 6, 8, 10]

In [74]:
seq=[1,2,3,4,5]
lambda var:var*2
list(map(lambda var:var*2,seq))
list(filter(lambda item:item%2==0,seq))

[2, 4]

In [77]:
import numpy as np
my_list=[1,2,3]
print(my_list)
np.array(my_list)



[1, 2, 3]


array([1, 2, 3])

In [79]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
print(my_matrix)
np.array(my_matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [82]:
np.zeros(3)

array([0., 0., 0.])

In [83]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [85]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [86]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [87]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [88]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [89]:
np.random.rand(5,5)

array([[0.95549328, 0.57404725, 0.4279711 , 0.36228632, 0.97113136],
       [0.6915591 , 0.17335518, 0.86095526, 0.1824327 , 0.36247626],
       [0.76067504, 0.47508552, 0.51911783, 0.91217519, 0.43900949],
       [0.46839718, 0.11915642, 0.14530571, 0.06418277, 0.87529172],
       [0.89631422, 0.75033048, 0.63948034, 0.46006313, 0.54202112]])

In [90]:
np.random.randn(5,5)

array([[ 0.38762133, -0.07265938, -0.32475652, -0.51871439,  0.32625873],
       [ 0.41924758,  1.20160099,  1.24836377,  0.34154969, -0.8539602 ],
       [ 0.51045328, -1.16174032, -0.56528881,  0.88518259, -0.27859552],
       [ 1.35919975,  0.1370446 , -0.52295742,  0.37048335, -0.91293229],
       [ 1.44055591,  2.28268449, -0.47160386, -0.1829041 ,  0.54782931]])

In [91]:
np.random.randint(1,100,10)

array([37, 10, 71, 24,  8, 28, 43, 31, 88, 75])

In [92]:
a=np.random.randint(1,100,10)
print(a)

[55 96 62 89 80 98 62 88 97 14]


In [94]:
arr=np.arange(25)
runnarr=np.random.randint(0,50,10)
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [97]:
runnarr.max()

39

In [98]:
runnarr.argmax()

1

In [99]:
runnarr.min()

0

In [100]:
runnarr.argmin()

2

In [101]:
arr.shape

(25,)

In [102]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [103]:
arr.reshape(1,25).shape

(1, 25)

In [104]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [105]:
arr.reshape(25,1).shape

(25, 1)

In [107]:
arr.dtype

dtype('int32')

In [108]:
arr=np.arange(0,10)
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [109]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [110]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [111]:
arr/arr

C:\Users\LUBNA\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [112]:
arr//arr

C:\Users\LUBNA\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [113]:
1/arr

C:\Users\LUBNA\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [114]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [115]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [119]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [117]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [118]:
np.log(arr)

C:\Users\LUBNA\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [121]:
arr=np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [122]:
arr[8]

8

In [123]:
arr[1:5]

array([1, 2, 3, 4])

In [124]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [125]:
arr[0:5]=100

In [126]:
print(arr)

[100 100 100 100 100   5   6   7   8   9  10]


In [127]:
arr>4

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [129]:
arr=np.arange(0,11)
arr>4


array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [130]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [131]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [132]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [133]:
np.fives(10)

AttributeError: module 'numpy' has no attribute 'fives'

In [136]:
arr=np.arange(0,41)
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80])

In [139]:
ar=np.arange(0,9)
ar.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [143]:
ar=np.arange(1,26)
ar.reshape(5,5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [144]:
ar[ar>12]

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [145]:
np.random.randn(25)

array([ 0.25675543,  0.13971407,  1.14330091,  0.13761   ,  1.3105194 ,
        0.57518014,  0.168598  , -0.14283313, -2.31396886,  0.9953844 ,
       -0.63019689, -0.03922356, -0.0211146 ,  1.64119007,  1.86943397,
       -1.65974658, -1.00024491,  0.71474325, -2.06689619,  0.77312189,
        0.03669525, -1.83509034,  1.30267541, -2.52158099, -0.08421409])

In [146]:
a=np.arange(10)
a[0:10]=5
print(a)

[5 5 5 5 5 5 5 5 5 5]
